# SPDX-FileCopyrightText: 2023 Filip Pokorný (thank you!!) Adapted by aaronkaplan
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Build and publish documentation"

on:
  push:
    branches:
      - publish

  pull_request:
    branches:
      - publish


  release:
    types:
      - published

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: "Install build dependencies"
        run: |
          pip install mkdocs-material mike lunr pygments mkdocstrings[python] mkdocs-material mkdocs-glightbox mkdocs-redirects mkdocs-minify-plugin ruamel.yaml


      - name: "Build docs without publishing"
        if: github.event_name == 'pull_request'
        run: |
          mkdocs build

      - name: "Build docs with version tag and publish"
        if: github.event_name == 'release'
        run: |
          mike deploy --push --update-aliases ${{ github.ref_name }} latest

      - name: "Build docs with branch tag and publish"
        if: github.event_name == 'push'
        run: |
          mike deploy --push ${{ github.ref_name }}
